impart/authentication/urls.py
# -*- coding: utf-8 -*-
"""
Routing for authentication.

.. moduleauthor:: bl
.. versionadded:: Acai_Berry
"""

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from authentication import views, forms

app_name = 'auth'

urlpatterns = [
    url(
        r'^login/$',
        views.LoginView.as_view(
            form_class=forms.ImpartAuthenticationForm),
        name="login"
    ),
    url(
        r'^logout/$',
        auth_views.logout,
        name='logout'
    ),
    url(
        r'^get_net_id/$',
        views.GetNetIDAjaxView.as_view(),
        name="getNetID"
    ),
    url(r'^ratelimit/$',
        views.RemoveLimitView.as_view(
            form_class=forms.RemoveRateLimitForm),
        name='ratelimit'),
]

impart/comm_crowd_sourcing/urls.py
# -*- coding: utf-8 -*-
"""
Routing for the Crowd Sourcing application.

.. moduleauthor:: sba
.. moduleauthor:: saj
.. versionadded:: Acai_Berry
"""

from django.conf.urls import url
from .views import AboutView

from .views import ContactMessageCreateView
from .views import FAQView
from .views import HomePageDetailView
from .views import ResearchQuestionApprovalUpdateView
from .views import ResearchQuestionCommentCreateView
from .views import ResearchQuestionCreateView
from .views import ResearchQuestionListView
from .views import ThankYouContactView
from .views import ThankYouView
from .views import UnsubscribeConfirmView
from .views import UnsubscribeEmailUpdateView

app_name = 'comm_crowd_sourcing'

urlpatterns = [
    url(
        r'^$$',
        HomePageDetailView.as_view(),
        name='index'
        ),
    url(
        r'^research_question/$',
        ResearchQuestionCreateView.as_view(),
        name='create'
        ),
    url(
        r'^list/(?P<topic_filter>\w+)$',
        ResearchQuestionListView.as_view(),
        name='list_filter'
        ),
    url(
        r'^list/$',
        ResearchQuestionListView.as_view(),
        name='list'
        ),
    url(
        r'^detail/(?P<pk>\d+)$',
        ResearchQuestionCommentCreateView.as_view(),
        name='comment_create'
        ),
    url(
        r'^approve/(?P<pk>\d+)$',
        ResearchQuestionApprovalUpdateView.as_view(),
        name='approve'
        ),
    url(
        r'^thank_you/$',
        ThankYouView.as_view(),
        name='thank_you'
        ),
    url(r'^about/',
        AboutView.as_view(),
        name='about'
        ),
    url(
        r'^contact_message/$',
        ContactMessageCreateView.as_view(),
        name='contact'
        ),
    url(
        r'^thank_you_contact/$',
        ThankYouContactView.as_view(),
        name='thank_you_contact'
        ),
    url(
        r'^faq/$',
        FAQView.as_view(),
        name='faq'
        ),
    url(
        r'^unsubscribe/(?P<pk>\d+)$',
        UnsubscribeEmailUpdateView.as_view(),
        name='unsubscribe'
        ),
    url(
        r'^unsubscribe_confirm/$',
        UnsubscribeConfirmView.as_view(),
        name='unsubscribe_confirm'
        ),
]

impart/crowd_sourcing/urls.py
# -*- coding: utf-8 -*-
"""
Routing for the Crowd Sourcing application.

.. moduleauthor:: sba
.. moduleauthor:: saj
.. versionadded:: Acai_Berry
"""

from django.conf.urls import url
from .views import AboutView

from .views import ContactMessageCreateView
from .views import FAQView
from .views import HomePageDetailView
from .views import ResearchQuestionCommentCreateView
from .views import ResearchQuestionCreateView
from .views import ResearchQuestionListView
from .views import ThankYouContactView
from .views import ThankYouView
from .views import UnsubscribeConfirmView
from .views import UnsubscribeEmailUpdateView

app_name = 'crowd_sourcing'

urlpatterns = [
    url(
        r'^$$',
        HomePageDetailView.as_view(),
        name='index'
        ),
    url(
        r'^research_question/$',
        ResearchQuestionCreateView.as_view(),
        name='create'
        ),
    url(
        r'^list/(?P<topic_filter>\w+)$',
        ResearchQuestionListView.as_view(),
        name='list_filter'
        ),
    url(
        r'^list/$',
        ResearchQuestionListView.as_view(),
        name='list'
        ),
    url(
        r'^detail/(?P<pk>\d+)$',
        ResearchQuestionCommentCreateView.as_view(),
        name='comment_create'
        ),
    url(
        r'^thank_you/$',
        ThankYouView.as_view(),
        name='thank_you'
        ),
    url(r'^about/',
        AboutView.as_view(),
        name='about'
        ),
    url(
        r'^contact_message/$',
        ContactMessageCreateView.as_view(),
        name='contact'
        ),
    url(
        r'^thank_you_contact/$',
        ThankYouContactView.as_view(),
        name='thank_you_contact'
        ),
    url(
        r'^faq/$',
        FAQView.as_view(),
        name='faq'
        ),
    url(
        r'^unsubscribe/(?P<pk>\d+)$',
        UnsubscribeEmailUpdateView.as_view(),
        name='unsubscribe'
        ),
    url(
        r'^unsubscribe_confirm/$',
        UnsubscribeConfirmView.as_view(),
        name='unsubscribe_confirm'
        ),
]

impart/crowd_sourcing_open/urls.py
# -*- coding: utf-8 -*-
"""
Routing for the Crowd Sourcing application.

.. moduleauthor:: sba
.. moduleauthor:: saj
.. versionadded:: Acai_Berry
"""

from django.conf.urls import url

from .views import AboutView
from .views import ContactMessageCreateView
from .views import FAQView
from .views import HomePageDetailView
from .views import ResearchQuestionApprovalUpdateView
from .views import ResearchQuestionCommentCreateView
from .views import ResearchQuestionCreateView
from .views import ResearchQuestionListView
from .views import ThankYouContactView
from .views import ThankYouView
from .views import UnsubscribeConfirmView
from .views import UnsubscribeEmailUpdateView

app_name = 'crowd_sourcing_open'

urlpatterns = [
    url(
        r'^$$',
        HomePageDetailView.as_view(),
        name='index'
        ),
    url(
        r'^research_question/$',
        ResearchQuestionCreateView.as_view(),
        name='create'
        ),
    url(
        r'^list/(?P<topic_filter>\w+)$',
        ResearchQuestionListView.as_view(),
        name='list_filter'
        ),
    url(
        r'^list/$',
        ResearchQuestionListView.as_view(),
        name='list'
        ),
    url(
        r'^detail/(?P<pk>\d+)$',
        ResearchQuestionCommentCreateView.as_view(),
        name='comment_create'
        ),
    url(
        r'^approve/(?P<pk>\d+)$',
        ResearchQuestionApprovalUpdateView.as_view(),
        name='approve'
        ),
    url(
        r'^thank_you/$',
        ThankYouView.as_view(),
        name='thank_you'
        ),
    url(r'^about/',
        AboutView.as_view(),
        name='about'
        ),
    url(
        r'^contact_message/$',
        ContactMessageCreateView.as_view(),
        name='contact'
        ),
    url(
        r'^thank_you_contact/$',
        ThankYouContactView.as_view(),
        name='thank_you_contact'
        ),
    url(
        r'^faq/$',
        FAQView.as_view(),
        name='faq'
        ),
    url(
        r'^unsubscribe/(?P<pk>\d+)$',
        UnsubscribeEmailUpdateView.as_view(),
        name='unsubscribe'
        ),
    url(
        r'^unsubscribe_confirm/$',
        UnsubscribeConfirmView.as_view(),
        name='unsubscribe_confirm'
        ),
]

impart/impart/urls.py
# -*- coding: utf-8 -*-
"""
Routing table for the overall project.
"""

from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

from crowd_sourcing.views import HomePageDetailView

admin.autodiscover()


urlpatterns = []
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(
            r'^__debug__/',
            include(debug_toolbar.urls)
        ),
    ]

urlpatterns += [
    url(r'^$',
        HomePageDetailView.as_view(), name='index'),
    url(r'^accounts/',
        include('authentication.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^crowd_sourcing/',
        include('crowd_sourcing.urls')),
    url(r'^crowd_sourcing_open/',
        include('crowd_sourcing_open.urls')),
    url(r'^comm_crowd_sourcing/',
        include('comm_crowd_sourcing.urls')),
    url(r'^signed/',
        include('signed_link.urls')),
    url(r'^autocomplete/',
        include('autocomplete_light.urls')),
    url('',
        # include('social.apps.django_app.urls')),
        include('social.apps.django_app.urls', namespace='social')),
]

impart/templates/_errors.html
{% load floppyforms %}

{% for error in form.non_field_errors %}
  <div class="alert alert-error">
    <a class="close" href="#" data-dismiss="alert">×</a>
      {{ error }}
  </div><!--- .alert.alert-error -->
{% endfor %}
{% for error in form|hidden_field_errors %}
  <div class="alert alert-error">
    <a class="close" href="#" data-dismiss="alert">×</a>
      {{ error }}
  </div><!--- .alert.alert-error -->
{% endfor %}

impart/templates/_footer_impart.html
<footer class="m_footer">
 <div id="desktop-footer">
  <div class="container">
      <p class="footer_ctsa">
      Dartmouth SYNERGY Clinical and Translational Science Institute is supported in part through the National Institutes of Health (NIH) Clinical and Translational Science Award (CTSA) program. The CTSA program is led by the NIH's National Center for Advancing Translational Sciences (NCATS). The content of this website is solely the responsibility of Dartmouth SYNERGY and does not necessarily represent the official views of the NIH.
      </p>
    </div>
  <div class="container">
  <ul class="list-unstyled list-inline">
    <li><a href="http://geiselmed.dartmouth.edu/">Geisel School of Medicine at Dartmouth</a></li>
    <li class="muted">•</li>
    <li><a href="http://dartmouth.edu">Dartmouth College</a></li>
    <li class="muted">•</li>
    <li><a href="http://www.dartmouth-hitchcock.org/">Dartmouth-Hitchcock Medical Center </a></li>
    <li class="muted">•</li>
    <li><a href="http://tdi.dartmouth.edu/">The Dartmouth Institute for Health Policy </a></li>
  </ul>
  <ul class="list-unstyled list-inline">
    <li><a href="http://engineering.dartmouth.edu/">Thayer School of Engineering</a></li>
    <li class="muted">•</li>
    <li><a href="http://www.tuck.dartmouth.edu/">Tuck School of Business </a></li>
    <li class="muted">•</li>
    <li><a href="http://cancer.dartmouth.edu/">Norris Cotton Cancer Center </a></li>
    <li class="muted">•</li>
    <li><a href="http://www.whiteriver.va.gov/">White River Junction VA Medical Center </a></li>
  </ul>
  <ul class="list-unstyled list-inline m_pd_tp_x">
    <li><a href="#">Sitemap</a></li>
    <li class="muted">•</li>
    <li><a href="{% url 'crowd_sourcing:about' %}">About this Site</a></li>
  </ul>
  <ul class="list-unstyled list-inline">
    <li><a href="#">Copyright © {% now "Y" %} Dartmouth College, Dartmouth-Hitchcock, All rights reserved.</a></li>
  </ul>
</div>
 </div>
 <div id="mobile-footer">
    <a class="list-unstyled list-inline m_pd_tp_x" href="{% url 'crowd_sourcing:about' %}">About this Site</a>
 </div>
</footer>

impart/templates/_header_comm_crowd_sourcing.html
{% load i18n %}

<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#impart-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="large_white_text" href="{% url 'comm_crowd_sourcing:index' %}">
      Impart
    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="impart-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'comm_crowd_sourcing:about' %}" class="nav_bar_labels pink_label">ABOUT</a></li>
      <li><a href="{% url 'comm_crowd_sourcing:contact' %}" class="nav_bar_labels green_label">CONTACT</a></li>
      {% if user.is_authenticated %}
        <li class="logged_in_text">
          Logged in as {{ user.get_full_name|default:user.username }} (via {% firstof provider "Dartmouth NetID" %})
        </li>
        <li><a class="btn btn-lg orange_button" href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>
      {% else %}
        <li><a class="btn btn-lg orange_button" href="{% url 'auth:login' %}?next={{ request.path }}">
        Log in</a></li>
      {% endif %}
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class="container-fluid nav_bottom_padding">
</div>

impart/templates/_header_crowd_sourcing.html
{% load i18n %}

<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#impart-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="large_white_text" href="{% url 'crowd_sourcing:index' %}">
      Impart
    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="impart-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'crowd_sourcing:about' %}" class="nav_bar_labels pink_label">ABOUT</a></li>
      <li><a href="{% url 'crowd_sourcing:contact' %}" class="nav_bar_labels green_label">CONTACT</a></li>
      {% if user.is_authenticated %}
        <li><a title="{% trans 'Logged in as' %} {{ user.get_username }}" class="btn btn-lg orange_button" href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
      {% else %}
        <li><a class="btn btn-lg orange_button" href="{% url 'auth:login' %}">Login</a>
      {% endif %}
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class="container-fluid nav_bottom_padding">
</div>

impart/templates/_header_crowd_sourcing_open.html
{% load i18n %}

<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#impart-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="large_white_text" href="{% url 'crowd_sourcing_open:index' %}">
      Impart
    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="impart-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'crowd_sourcing_open:about' %}" class="nav_bar_labels pink_label">ABOUT</a></li>
      <li><a href="{% url 'crowd_sourcing_open:contact' %}" class="nav_bar_labels green_label">CONTACT</a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<div class="container-fluid nav_bottom_padding">
</div>

impart/templates/_header_impart.html
<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#impart-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="large_white_text" href="{% url 'crowd_sourcing:index' %}">
      Impart
    </a>
  </div>
</div><!-- /.container-fluid -->
</nav>
<div class="container-fluid nav_bottom_padding">
</div>

impart/templates/_messages.html
{% if messages %}
  <div id="message_box" class="row">
    <div class="col-sm-3 col-xs-12"></div>
    <ul class="messages col-sm-6 col-xs-12">
      {% for message in messages %}
        <li id="message_{{ forloop.counter }}"
          {% if message.tags %} class="{{ message.tags }}"{% endif %}>
          {{ message }}
        </li>
      {% endfor %}
    </ul>
    <div class="col-sm-3 col-xs-12"></div>
  </div>
{% endif %}

impart/templates/base.html
{% load staticfiles %}<!DOCTYPE html>{% spaceless %}{% endspaceless %}
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content={% block page_description %}"{{ PUBLIC_WEBSITE_NAME }} {{ WEB_SYSTEM_NAME }} is a tool for medical researchers at the Geisel School of Medicine at Dartmouth College and is funded in part by the CTSA grant."{% endblock page_description %}>

    <title>{% block title %}{{ WEB_SYSTEM_NAME }}{% endblock title %}</title>

    {% block css %}
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
      {# <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet"> #}
      <link href="{% static 'css/dartmouth.css' %}" rel="stylesheet"> {# Modified bootstrap styles from Jorge #}
      <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" rel="stylesheet">
      <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
      <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700' rel='stylesheet' type='text/css'>
      <link href='//fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
      <link href="{% static 'css/m_class.css' %}" rel="stylesheet">
      <link href="{% static 'css/m_project.css' %}" rel="stylesheet">
      <link href="{% static 'css/input.css' %}" rel="stylesheet">
      <link href="{% static 'css/m_overrides.css' %}" rel="stylesheet">
      <link href="{% static 'css/crowd_source.css' %}" rel="stylesheet">
      <link href="{% static 'css/impart.css' %}" rel="stylesheet">
    {% endblock css %}

    {% block extra_css %} {% endblock extra_css %}
    <script src="https://www.google.com/recaptcha/api.js" async defer></script> 
  </head>

  <body>

    {% block body_wrapper %}
      <div id='all_body' class='wrapper'>
    {% endblock body_wrapper %}

    {% block header %}
      {% include '_header_impart.html' %}
    {% endblock header %}

    {% block side_nav %}{% endblock side_nav %}

    {% block pre_content %}
      <div id="main_body" class="m_maint container-fluid synergy_headers" role="main" aria-label="Main content">
    {% endblock pre_content %}

    {% block message_box %}
      {% include '_messages.html' %}
    {% endblock message_box %}

    {% block page_title %}{% endblock page_title %}

    <!-- Header needs to go in here in order for the footer to work -->
    {% block content %}{% endblock content %}

    {% block post_content %}
      </div>{# end main_body #}
      <div class="push"></div>
      </div>{# end wrapper #}
    {% endblock post_content %}

    {% block footer %}
      {% include '_footer_impart.html' %}
    {% endblock footer %}

    {% block js %}
      <script src="//code.jquery.com/jquery-latest.js"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery.droptabs.js' %}"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
      <script src="{% static 'js/project.js' %}"></script>
      {% include 'autocomplete_light/static.html' %}
    {% endblock js %}

    {% block piwik %}
      <script type="text/javascript">
      var _paq = _paq || [];
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
          //var u = (("https:" == document.location.protocol) ? "https" : "http") + "://informatics.dartmouth.edu/piwik//";
          var u = "https://informatics.dartmouth.edu/piwik//"
          _paq.push(['setTrackerUrl', u + 'piwik.php']);
          _paq.push(['setSiteId', 1]);
          var d = document,
              g = d.createElement('script'),
              s = d.getElementsByTagName('script')[0];
          g.type = 'text/javascript';
          g.defer = true;
          g.async = true;
          g.src = u + 'piwik.js';
          s.parentNode.insertBefore(g, s);
      })();
      </script>
      <noscript>
          <p><img src="//informatics.dartmouth.edu/piwik/piwik.php?idsite=1" style="border:0" alt="" /></p>
      </noscript>
    {% endblock piwik %}

    {% block extra_js %} {% endblock extra_js %}

  </body>
</html>
{% spaceless %}
{% endspaceless %}

impart/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load floppyforms %}
{% load i18n %}

{% block content %}
  <div class="col-md-2 col-xs-12"></div>

  <div class="col-md-8 col-xs-12">
  <h2 class="centered"><a href="{% url 'crowd_sourcing:index' %}">{% trans "Crowd Sourcing" %}</a></h2>
  </div>
  <div class="col-md-2 col-xs-12"></div>
{% endblock content %} 