impart/crowd_sourcing/urls.py
# -*- coding: utf-8 -*-
"""
Routing for the Crowd Sourcing application.

.. moduleauthor:: sba
.. moduleauthor:: saj
.. versionadded:: Acai_Berry
"""

from django.conf.urls import url
from .views import AboutView

from .views import ContactMessageCreateView
from .views import FAQView
from .views import HomePageDetailView
from .views import ResearchQuestionCommentCreateView
from .views import ResearchQuestionCreateView
from .views import ResearchQuestionListView
from .views import ThankYouContactView
from .views import ThankYouView
from .views import UnsubscribeConfirmView
from .views import UnsubscribeEmailUpdateView

app_name = 'crowd_sourcing'

urlpatterns = [
    url(
        r'^$$',
        HomePageDetailView.as_view(),
        name='index'
        ),
    url(
        r'^research_question/$',
        ResearchQuestionCreateView.as_view(),
        name='create'
        ),
    url(
        r'^list/(?P<topic_filter>\w+)$',
        ResearchQuestionListView.as_view(),
        name='list_filter'
        ),
    url(
        r'^list/$',
        ResearchQuestionListView.as_view(),
        name='list'
        ),
    url(
        r'^detail/(?P<pk>\d+)$',
        ResearchQuestionCommentCreateView.as_view(),
        name='comment_create'
        ),
    url(
        r'^thank_you/$',
        ThankYouView.as_view(),
        name='thank_you'
        ),
    url(r'^about/',
        AboutView.as_view(),
        name='about'
        ),
    url(
        r'^contact_message/$',
        ContactMessageCreateView.as_view(),
        name='contact'
        ),
    url(
        r'^thank_you_contact/$',
        ThankYouContactView.as_view(),
        name='thank_you_contact'
        ),
    url(
        r'^faq/$',
        FAQView.as_view(),
        name='faq'
        ),
    url(
        r'^unsubscribe/(?P<pk>\d+)$',
        UnsubscribeEmailUpdateView.as_view(),
        name='unsubscribe'
        ),
    url(
        r'^unsubscribe_confirm/$',
        UnsubscribeConfirmView.as_view(),
        name='unsubscribe_confirm'
        ),
]

impart/impart/urls.py
# -*- coding: utf-8 -*-
"""
Routing table for the overall project.
"""

from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

from crowd_sourcing.views import HomePageDetailView

admin.autodiscover()


urlpatterns = []
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(
            r'^__debug__/',
            include(debug_toolbar.urls)
        ),
    ]

urlpatterns += [
    url(r'^$',
        HomePageDetailView.as_view(), name='index'),
    url(r'^accounts/',
        include('authentication.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^crowd_sourcing/',
        include('crowd_sourcing.urls')),
    url(r'^crowd_sourcing_open/',
        include('crowd_sourcing_open.urls')),
    url(r'^comm_crowd_sourcing/',
        include('comm_crowd_sourcing.urls')),
    url(r'^signed/',
        include('signed_link.urls')),
    url(r'^autocomplete/',
        include('autocomplete_light.urls')),
    url('',
        # include('social.apps.django_app.urls')),
        include('social.apps.django_app.urls', namespace='social')),
]

impart/crowd_sourcing/views.py
# -*- coding: utf-8 -*-
"""
Views for the Crowd Sourcing app.

.. moduleauthor:: saj
.. versionadded:: Acai_Berry
"""

import logging

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect

from django.shortcuts import get_object_or_404
from django.template.response import ContentNotRenderedError
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from authentication.views import ImpartLoginRequired
import email_utils.constants
from email_utils.models import ImpartMailer
from email_utils.models import EmailNotification
from utils.mixins import ChangeActionMessageMixin
from utils.utils import get_client_ip

from .forms import ContactMessageForm
from .forms import ResearchQuestionCommentForm
from .forms import ResearchQuestionForm
from .models import ContactMessage
from .models import FAQ
from .models import ResearchQuestion
from .models import ResearchQuestionComment
from .models import ResearchQuestionTopicChoiceField
from .models import ResearchQuestionVote

log = logging.getLogger(__name__)


class ResearchQuestionCreateView(ImpartLoginRequired, CreateView):
    """Allow a user to submit a crowd sourcing research question."""

    model = ResearchQuestion
    form_class = ResearchQuestionForm
    template_name = 'shared/research_question_create.html'
    success_url = reverse_lazy('crowd_sourcing:thank_you')

    def get_form(self, form_class=ResearchQuestionForm):
        """
        Inject user from the request into the form.

        :param class ResearchQuestionForm: Type of form to retrieve.
        :returns: The retrieved form, with user injected.
        :rtype: ResearchQuestionForm
        """

        form = super(ResearchQuestionCreateView, self).get_form(
            ResearchQuestionForm)
        form.instance.user = self.request.user
        return form

    def post(self, *args, **kwargs):
        """
        Extend to set the IP address in the post array.

        If the user opted for email notifications add her email to
        the NEW_QUESTION_NOTIFY list if the email is not
        already in the table.

        Notify users on the mailing list about the new question.

        :param *args: Optional set of positional arguments to pass to super().
        :param **kwargs: Optional set of keyword arguments to pass to super().
        :returns: Destination.
        :rtype: HttpResponse or HttpResponseRedirect
        """

        post_data = self.request.POST.copy()
        post_data['ip_address'] = get_client_ip(self.request)

        self.request.POST = post_data

        if self.request.POST.get("receive_notifications"):
            if EmailNotification.objects.filter(
                user=self.request.user,
                notification_type=email_utils.constants.NEW_QUESTION_NOTIFY).count() == 0:
                email_notification = EmailNotification(
                    notification_type=email_utils.constants.NEW_QUESTION_NOTIFY,
                    user=self.request.user,
                    extra=0)
                email_notification.save()

        return super(
            ResearchQuestionCreateView, self).post(*args, **kwargs)

    def get_success_url(self):
        """Override to send notifications to user in the mailing list."""

        ImpartMailer().new_approved_question(
            self.object, self.request, 'crowd_sourcing')

        return super(ResearchQuestionCreateView, self).get_success_url()


class ResearchQuestionListView(ListView):
    """Show a list of submitted research questions."""

    model = ResearchQuestion
    template_name = 'shared/research_question_list.html'
    context_object_name = 'questions'

    def get_queryset(self):
        """
        Get all research questions and info for table.

        :returns: queryset of all research questions.
        :rtype: QuerySet
        """

        return ResearchQuestion.get_questions()

    def get_context_data(self, **kwargs):
        """
        Add header label to the context.

        :param **kwargs: Optional set of keyword arguments to pass to super().
        :returns: With header label.
        :rtype: Context
        """

        context = super(
            ResearchQuestionListView, self).get_context_data(**kwargs)

        context['topic_list'] = ResearchQuestionTopicChoiceField.objects.all()
        context['questions'] = self.questions
        context['current_filter'] = self.topic_filter
        context['active_tab'] = self.sort_type

        return context

    def get(self, *args, **kwargs):
        """
        Extend to get the topic to filter on.

        :param *args: Optional set of positional arguments to pass to super().
        :param **kwargs: Optional set of keyword arguments to pass to super().
        :returns: Destination.
        :rtype: HTTPResponse or HttpResponseRedirect
        """

        self.topic_filter = self.request.GET.get('topic_filter')
        self.sort_type = self.request.GET.get('sort_type')
        if not self.sort_type:
            self.sort_type = 'newest'
        if self.topic_filter == 'all':
            self.topic_filter = None

        self.questions = ResearchQuestion.get_questions(
            self.topic_filter, self.sort_type)

        return super(ResearchQuestionListView, self).get(
            *args, **kwargs)


class ResearchQuestionCommentCreateView(
        ImpartLoginRequired, ChangeActionMessageMixin, CreateView):
    """
    Show information about a research question and allow for comment entry.
    """

    model = ResearchQuestionComment
    form_class = ResearchQuestionCommentForm
    template_name = 'shared/research_question_detail.html'
    success_msg = _('Thanks! Your comment was added.')

    def get_form(self, form_class=ResearchQuestionCommentForm):
        """
        Inject user from the request into the form.

        :param class ResearchQuestionCommentForm: Type of form to retrieve.
        :returns: The retrieved form, with user injected.
        :rtype: ResearchQuestionCommentForm
        """

        form = super(ResearchQuestionCommentCreateView, self).get_form(
            ResearchQuestionCommentForm)
        form.instance.user = self.request.user
        return form

    def get_success_url(self):
        """ Provide the success URL with the current question ID."""
        return reverse(
            'crowd_sourcing:comment_create', kwargs={'pk': self.question.id})

    def get_context_data(self, **kwargs):
        """
        Get question information.

        :param **kwargs: Optional set of keyword arguments to pass to super().
        :returns: With header label.
        :rtype: Context
        """

        context = super(
            ResearchQuestionCommentCreateView, self).get_context_data(**kwargs)
        context['question'] = self.question
        context['comments'] = self.comments

        return context

    def post(self, *args, **kwargs):
        """
        Extend to get the question information.

        Get comments for the question to show in the comments table.
        Copy the immutable POST data, set the IP Address and question ID and
        put it back in self.request.POST when the form is submitted.

        Overwrite the vote value in the question object with the value just
        submitted to get around a bug where the vote isn't being displayed on
        the form after returning after a validation error.

        Only save a vote if the comments form posted successfully. This is
        determined with a try/except looking for the ContentNotRenderedError
        exception, which is thrown when the response is accessed after
        an unsuccessful post.

        :param *args: Optional set of positional arguments to pass to super().
        :param **kwargs: Optional set of keyword arguments to pass to super().
        :returns: Destination.
        :rtype: HttpResponse or HttpResponseRedirect
        """

        self.question_id = self.kwargs.pop('pk')

        self.question = ResearchQuestion.get_question_details(
            self.request, self.question_id)
        self.comments = ResearchQuestionComment.get_comments_for_question(
            question_id=self.question_id)

        post_data = self.request.POST.copy()
        post_data['ip_address'] = get_client_ip(self.request)
        post_data['question'] = self.question.id

        if 'vote' in self.request.POST:
            self.question.current_vote = bool(self.request.POST['vote'])

        self.request.POST = post_data

        self.response = super(
            ResearchQuestionCommentCreateView, self).post(
            *args, **kwargs)

        log.info(
            'User from IP Address: {0} left a comment for question {1}'.format(
                post_data['ip_address'], post_data['question']))

        # Refer to the method comment.
        try:
            log.info('Post response: {0}'.format(self.response))
        except ContentNotRenderedError:
            log.info('Did not post.')
        else:
            self.question = self.save_vote()

        return self.response

    def get(self, *args, **kwargs):
        """
        Extend to get the question information.

        Increase the view count for the question by 1.  This currently does not
        attempt to filter view counts from web crawlers.

        :param *args: Optional set of positional arguments to pass to super().
        :param **kwargs: Optional set of keyword arguments to pass to super().
        :returns: Destination.
        :rtype: HttpResponse or HttpResponseRedirect
        """

        self.question_id = self.kwargs.pop('pk')

        self.question = ResearchQuestion.get_question_details(
            self.request, self.question_id)

impart/crowd_sourcing/templates/crowd_sourcing/base_crowd_sourcing.html
{% extends "base.html" %}
{% load staticfiles %}

    {% block header %}
      {% include '_header_crowd_sourcing.html' %}
    {% endblock header %}

impart/crowd_sourcing/templates/crowd_sourcing/index.html
{% extends "crowd_sourcing/base_crowd_sourcing.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
  <div class="col-md-1 col-xs-12"></div>

  <div class="col-md-10 col-xs-12 home_font">
    <div class="image">
        <img src="{{ STATIC_URL }}img/main_page_image_cropped.png" width="100%" height="100%" />
        <div class="main_text title_image_font_large">
          Research question<br />platform for<br />
            <span class="green_text">clinicians</span> and
            <span class="green_text">scientists</span>
            <div class="title_image_font_small" id="title_image_font_small">
              The Impart Crowd Sourcing tool allows groups to come to a consensus.
            </div>
            <div id="main_buttons">
            <a class="btn btn-lg main_button" href="{% url 'crowd_sourcing:create' %}">{% trans IMPART_SUBMIT_QUESTION %}</a>
            <br />
            <a class="btn btn-lg main_button" href="{% url 'crowd_sourcing:list' %}">{% trans IMPART_VIEW_QUESTIONS %}</a>
            </div>
        </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="col-md-8 col-xs-12">
          <div class="container_fluid">
            <div class="row-fluid">
              <h3 class="blue_bottom_border_thin"><u>How It Works</u></h3>
            </div>
            <div class="row-fluid">
              <div class="col-md-2 col-xs-12 row_top_padding">
                <img src="{{ STATIC_URL }}img/microscope.png">
              </div>
              <div class="col-md-10 col-xs-12 row_top_padding row_bottom_padding">
                Influence &amp; Explore<br />
                <span class="light_font">Researchers at The Dartmouth Institute seek input from clinicians and basic scientists whose work experience likely inspires insightful questions that warrant exploration through population data research</span>
              </div>
            </div>
            <div class="row-fluid">
              <div class="col-md-2 col-xs-12 row_top_padding">
                <img src="{{ STATIC_URL }}img/question_mark.png">
              </div>
              <div class="col-md-10 col-xs-12 row_top_padding row_bottom_padding">
                {% trans IMPART_SUBMIT_QUESTION %}<br />
                <span class="light_font">It doesn't matter if it's a question, sharing your idea is the first step toward bringing your idea to life.</span>
              </div>
            </div>
            <div class="row-fluid">
              <div class="col-md-2 col-xs-12 row_top_padding">
                <img src="{{ STATIC_URL }}img/comment_bubbles.png">
              </div>
              <div class="col-md-10 col-xs-12 row_top_padding row_bottom_padding">
                Comment &amp; Vote<br />
                <span class="light_font">Deciding which of these questions are the best is in your hands.  Go ahead and vote on the ones you love, and help our researchers explore their question through population data.</span>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-xs-12">
          <div class="container_fluid">
            <div class="row-fluid">
              <h3 class="pink_bottom_border_thin"><u>Latest Question</u></h3>
            </div>
            <div class="row-fluid row_top_padding">
              {% if question %}
              <table class="table-bordered box_font">
                <tr>
                    <td class="box_padding">
                      {{ question.question }}
                    <br /><br />
                    By {{ question.user.first_name }} {{ question.user.last_name }}
                    ({{ question.created|date:"M d, Y" }})
                    </td>
                </tr>
                <tr>
                  <td class="box_padding right-side"><a href="{% url 'crowd_sourcing:list' %}">Read more &gt;</a></td>
                </tr>
              </table>
              {% else %}
                    No questions yet.
              {% endif %}
            </div>
            <div class="row-fluid row_top_padding row_bottom_padding">
              <h3 class="green_bottom_border_thin row_bottom_padding_small"><u>FAQ</u></h3>
              <table class="table-bordered box_font box_padding">
                {% for faq in faqs %}
                  <tr>
                    <td class="box_padding">{{ faq.question }}</td>
                  </tr>
                {% endfor %}
                <tr>
                  <td class="box_padding right-side"><a href="{% url 'crowd_sourcing:faq' %}">Read more &gt;</a></td>
                </tr>
              </table>
            </div>
          </div>
        </div>
    </div>  
  </div>
  <div class="col-md-1 col-xs-12"></div>
{% endblock content %} 

impart/crowd_sourcing/templates/crowd_sourcing/thank_you.html
{% extends "crowd_sourcing/base_crowd_sourcing.html" %}
{% load i18n %}

{% block content %}
  <div class="col-md-{{ FORMS_LEFT_GUTTER }} col-xs-12"></div>
    <h1 class="m_sections_title m_fsize2 text-center">Thank You</h1>
    <br />
    <p class="centered font_size_14">
        Thank you for submitting a question!
    </p>
    <br />
    <p class="centered">
        <a class="btn btn-lg orange_button" href="{% url 'crowd_sourcing:list' %}">
            {% trans IMPART_VIEW_SUBMITTED_QUESTIONS %}
        </a>
    </p>
  <div class="col-md-{{ FORMS_LEFT_GUTTER }} col-xs-12"></div>
{% endblock content %}